// https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

const extensions = [
  { extension: "aac", mimes: ["audio/aac"], type: "audio" },
  { extension: "abw", mimes: ["application/x-abiword"], type: "text" },
  { extension: "arc", mimes: ["application/x-freearc"], type: "comperssed" },
  { extension: "avi", mimes: ["video/x-msvideo"], type: "video" },
  { extension: "azw", mimes: ["application/vnd.amazon.ebook"], type: "ebook" },
  { extension: "bin", mimes: ["application/octet-stream"], type: "binary" },
  { extension: "bmp", mimes: ["image/bmp"], type: "system" },
  { extension: "bz", mimes: ["application/x-bzip"], type: "compressed" },
  { extension: "bz2", mimes: ["application/x-bzip2"], type: "compressed" },
  { extension: "cda", mimes: ["application/x-cdf"], type: "audio" },
  { extension: "csh", mimes: ["application/x-csh"], type: "misc" },
  { extension: "css", mimes: ["text/css"], type: "code" },
  { extension: "csv", mimes: ["text/csv"], type: "data" },
  { extension: "doc", mimes: ["application/msword"], type: "text" },
  {
    extension: "docx",
    mimes: [
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ],
    type: "text",
  },
  { extension: "eot", mimes: ["application/vnd.ms-fontobject"], type: "font" },
  { extension: "epub", mimes: ["application/epub+zip"], type: "ebook" },
  { extension: "gz", mimes: ["application/gzip"], type: "compressed" },
  { extension: "gif", mimes: ["image/gif"], type: "image" },
  { extension: "html", mimes: ["text/html"], type: "code" },
  { extension: "ico", mimes: ["image/vnd.microsoft.icon"], type: "image" },
  { extension: "ics", mimes: ["text/calendar"], type: "misc" },
  { extension: "jar", mimes: ["application/java-archive"], type: "executable" },
  { extension: "jpeg", mimes: ["image/jpeg"], type: "image" },
  { extension: "js", mimes: ["text/javascript"], type: "code" },
  { extension: "json", mimes: ["application/json"], type: "data" },
  { extension: "mid", mimes: ["audio/midi", "audio/x-midi"], type: "audio" },
  { extension: "mjs", mimes: ["text/javascript"], type: "code" },
  { extension: "mp3", mimes: ["audio/mpeg"], type: "audio" },
  { extension: "mp4", mimes: ["video/mp4"], type: "video" },
  { extension: "mpeg", mimes: ["video/mpeg"], type: "video" },
  {
    extension: "mpkg",
    mimes: ["application/vnd.apple.installer+xml"],
    type: "compressed",
  },
  {
    extension: "odp",
    mimes: ["application/vnd.oasis.opendocument.presentation"],
    type: "presentation",
  },
  {
    extension: "ods",
    mimes: ["application/vnd.oasis.opendocument.spreadsheet"],
    type: "spreadsheet",
  },
  {
    extension: "odt",
    mimes: ["application/vnd.oasis.opendocument.text"],
    type: "text",
  },
  { extension: "oga", mimes: ["audio/ogg"], type: "audio" },
  { extension: "ogv", mimes: ["video/ogg"], type: "video" },
  { extension: "ogx", mimes: ["application/ogg"], type: "video" },
  { extension: "opus", mimes: ["audio/opus"], type: "font" },
  { extension: "otf", mimes: ["font/otf"], type: "" },
  { extension: "png", mimes: ["image/png"], type: "" },
  { extension: "pdf", mimes: ["application/pdf"], type: "" },
  { extension: "php", mimes: ["application/x-httpd-php"], type: "" },
  { extension: "ppt", mimes: ["application/vnd.ms-powerpoint"], type: "" },
  {
    extension: "pptx",
    mimes: [
      "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    ],
    type: "",
  },
  { extension: "rar", mimes: ["application/vnd.rar"], type: "" },
  { extension: "rtf", mimes: ["application/rtf"], type: "" },
  { extension: "sh", mimes: ["application/x-sh"], type: "" },
  { extension: "svg", mimes: ["image/svg+xml"], type: "" },
  { extension: "swf", mimes: ["application/x-shockwave-flash"], type: "" },
  { extension: "tar", mimes: ["application/x-tar"], type: "" },
  { extension: "tif", mimes: ["image/tiff"], type: "" },
  { extension: "ts", mimes: ["video/mp2t"], type: "" },
  { extension: "ttf", mimes: ["font/ttf"], type: "" },
  { extension: "txt", mimes: ["text/plain"], type: "" },
  { extension: "vsd", mimes: ["application/vnd.visio"], type: "" },
  { extension: "wav", mimes: ["audio/wav"], type: "" },
  { extension: "weba", mimes: ["audio/webm"], type: "" },
  { extension: "webm", mimes: ["video/webm"], type: "" },
  { extension: "webp", mimes: ["image/webp"], type: "" },
  { extension: "woff", mimes: ["font/woff"], type: "" },
  { extension: "woff2", mimes: ["font/woff2"], type: "" },
  { extension: "xhtml", mimes: ["application/xhtml+xml"], type: "" },
  { extension: "xls", mimes: ["application/vnd.ms-excel"], type: "" },
  {
    extension: "xlsx",
    mimes: [
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ],
    type: "",
  },
  {
    extension: "xml",
    mimes: [
      "application/xml,text/xml",
      "application/atom+xml",
      "application/xml",
    ],
    type: "",
  },
  { extension: "xul", mimes: ["application/vnd.mozilla.xul+xml"], type: "" },
  { extension: "zip", mimes: ["application/zip"], type: "" },
  {
    extension: "3gp",
    mimes: ["audio/video", "video/3gpp", "audio/3gpp"],
    type: "",
  },
  {
    extension: "3g2",
    mimes: ["audio/video", "video/3gpp2", "audio/3gpp2"],
    type: "",
  },
  { extension: "7z", mimes: ["application/x-7z-compressed"], type: "" },
];

export default extensions;
